### PR TITLE
fix errors that makes ide-reason.json never work

### PR DESCRIPTION
**Pull request by clouds56**
The readFileConf have to be called in startServerProcess since projectPath only available there

### CODE REVIEW

**Comment by clouds56** [comment]
Not sure if this would make #9 regress

**Comment by alex35mil** [comment]
@clouds56 Things are going to change a bit. Check out https://github.com/reasonml-editor/atom-ide-reason/pull/11 & current `dev` branch.

**Comment by clouds56** [comment]
Sorry, haven't notice that.
What's the status of per project configuration now? I see some progress on dev branch.

BTW, the readFileConf still could not read current file (shown in this PR)
https://github.com/reasonml-editor/atom-ide-reason/blob/dev/lib/main.js#L50

**Comment by alex35mil** [comment]
AFAIK @zaaack is working on it.

**Comment by zaaack** [comment]
Hi, all, I just put my work here, https://github.com/reasonml-editor/atom-ide-reason/pull/16  so you can review it.

**Pull request closed without merging**
