### PR TITLE
Bump RLS to 1.0.2

### PR DESCRIPTION
**Pull request by alex35mil**

### CODE REVIEW

**Comment by zaaack** [comment]
Thanks!

**Comment by alex35mil** [comment]
@zaaack ping, can you release it when you get a chance? thanks!

**Comment by zaaack** [comment]
@alexfedoseev Ok, I'm wondering when can we release stable version?

**Comment by alex35mil** [comment]
@zaaack I guess we can now since RLS is stable and I didn't notice any issues specific to this plugin.
I have one `refmt` related bug on my list (reported in discord) but AFAICT it's not related to this plugin but to `atom-ide-ui`.

**Comment by zaaack** [comment]
@alexfedoseev Great, I have just published a new beta version, ide-reason@v1.0.0-beta.3 already... 😅

**Comment by alex35mil** [comment]
Haha ok, then I will look into this refmt bug this weekend and ping you 👍

**Pull request merged**
