### PR TITLE
add toolchainPath support

### PR DESCRIPTION
**Pull request by clouds56**

### CODE REVIEW

**Comment by clouds56** [comment]
By using this patch, we could write "toolchainPath" like before and it would auto detect tools in path and add it to config (with low priority, could be override with specific path settings like `path.refmt` in the same file)

**Comment by zaaack** [comment]
I'm not sure this is needed anymore, the configuration already contains the path of  `env` binary, you can easily override it with a custom env bin like:

 `"env": "./.atom/reason-env.sh"`

**Comment by zaaack** [comment]
@clouds56 Do you still need to merge this PR? Can you try something like this?
```sh
"env": "env PATH=/some/extra/path:$PATH"
```

**Comment by clouds56** [comment]
There're some slight difference.
The `env` changes path (change the path means a little more than change tools path), but my patch detect tools and set correspond `setting.reason.path.*` (and also no need of external script)
If https://github.com/freebroccolo/ocaml-language-server/pull/101 got merged/fixed, changing content in "./.atom/reason-env.sh" would not trigger ocamlmerlin-server to restart automatically (the path of env is literally the same.

this is just a proposal, it's fine that you don't like it (just a bit more complicated when config)

EDIT: and AFSIK the "env" doesn't even called in ocaml-language-server for starting ocamlmerlin-server, it is only used for `giveProjectEnv` request.

**Pull request merged**
